/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BundleDeleteBody,
  BundleDeleteResponse,
  BundleReadBody,
  BundleReadResponse,
  BundleWriteBody,
  BundleWriteResponse,
  Status,
} from '../models/index';
import {
    BundleDeleteBodyFromJSON,
    BundleDeleteBodyToJSON,
    BundleDeleteResponseFromJSON,
    BundleDeleteResponseToJSON,
    BundleReadBodyFromJSON,
    BundleReadBodyToJSON,
    BundleReadResponseFromJSON,
    BundleReadResponseToJSON,
    BundleWriteBodyFromJSON,
    BundleWriteBodyToJSON,
    BundleWriteResponseFromJSON,
    BundleWriteResponseToJSON,
    StatusFromJSON,
    StatusToJSON,
} from '../models/index';

export interface BundleDeleteRequest {
    tenantId: string;
    body: BundleDeleteBody;
}

export interface BundleReadRequest {
    tenantId: string;
    body: BundleReadBody;
}

export interface BundleWriteRequest {
    tenantId: string;
    body: BundleWriteBody;
}

/**
 * 
 */
export class BundleApi extends runtime.BaseAPI {

    /**
     * Creates request options for bundleDelete without sending the request
     */
    async bundleDeleteRequestOpts(requestParameters: BundleDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling bundleDelete().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling bundleDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/tenants/{tenant_id}/bundle/delete`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BundleDeleteBodyToJSON(requestParameters['body']),
        };
    }

    /**
     * delete bundle
     */
    async bundleDeleteRaw(requestParameters: BundleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BundleDeleteResponse>> {
        const requestOptions = await this.bundleDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BundleDeleteResponseFromJSON(jsonValue));
    }

    /**
     * delete bundle
     */
    async bundleDelete(requestParameters: BundleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BundleDeleteResponse> {
        const response = await this.bundleDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for bundleRead without sending the request
     */
    async bundleReadRequestOpts(requestParameters: BundleReadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling bundleRead().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling bundleRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/tenants/{tenant_id}/bundle/read`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BundleReadBodyToJSON(requestParameters['body']),
        };
    }

    /**
     * read bundle
     */
    async bundleReadRaw(requestParameters: BundleReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BundleReadResponse>> {
        const requestOptions = await this.bundleReadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BundleReadResponseFromJSON(jsonValue));
    }

    /**
     * read bundle
     */
    async bundleRead(requestParameters: BundleReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BundleReadResponse> {
        const response = await this.bundleReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for bundleWrite without sending the request
     */
    async bundleWriteRequestOpts(requestParameters: BundleWriteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling bundleWrite().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling bundleWrite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/tenants/{tenant_id}/bundle/write`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BundleWriteBodyToJSON(requestParameters['body']),
        };
    }

    /**
     * write bundle
     */
    async bundleWriteRaw(requestParameters: BundleWriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BundleWriteResponse>> {
        const requestOptions = await this.bundleWriteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BundleWriteResponseFromJSON(jsonValue));
    }

    /**
     * write bundle
     */
    async bundleWrite(requestParameters: BundleWriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BundleWriteResponse> {
        const response = await this.bundleWriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
