/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PartialWriteBody,
  SchemaListBody,
  SchemaListResponse,
  SchemaPartialWriteResponse,
  SchemaReadBody,
  SchemaReadResponse,
  SchemaWriteBody,
  SchemaWriteResponse,
  Status,
} from '../models/index';
import {
    PartialWriteBodyFromJSON,
    PartialWriteBodyToJSON,
    SchemaListBodyFromJSON,
    SchemaListBodyToJSON,
    SchemaListResponseFromJSON,
    SchemaListResponseToJSON,
    SchemaPartialWriteResponseFromJSON,
    SchemaPartialWriteResponseToJSON,
    SchemaReadBodyFromJSON,
    SchemaReadBodyToJSON,
    SchemaReadResponseFromJSON,
    SchemaReadResponseToJSON,
    SchemaWriteBodyFromJSON,
    SchemaWriteBodyToJSON,
    SchemaWriteResponseFromJSON,
    SchemaWriteResponseToJSON,
    StatusFromJSON,
    StatusToJSON,
} from '../models/index';

export interface SchemasListRequest {
    tenantId: string;
    body: SchemaListBody;
}

export interface SchemasPartialWriteRequest {
    tenantId: string;
    body: PartialWriteBody;
}

export interface SchemasReadRequest {
    tenantId: string;
    body: SchemaReadBody;
}

export interface SchemasWriteRequest {
    tenantId: string;
    body: SchemaWriteBody;
}

/**
 * 
 */
export class SchemaApi extends runtime.BaseAPI {

    /**
     * Creates request options for schemasList without sending the request
     */
    async schemasListRequestOpts(requestParameters: SchemasListRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling schemasList().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling schemasList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/tenants/{tenant_id}/schemas/list`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SchemaListBodyToJSON(requestParameters['body']),
        };
    }

    /**
     * list schema
     */
    async schemasListRaw(requestParameters: SchemasListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaListResponse>> {
        const requestOptions = await this.schemasListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaListResponseFromJSON(jsonValue));
    }

    /**
     * list schema
     */
    async schemasList(requestParameters: SchemasListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaListResponse> {
        const response = await this.schemasListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for schemasPartialWrite without sending the request
     */
    async schemasPartialWriteRequestOpts(requestParameters: SchemasPartialWriteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling schemasPartialWrite().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling schemasPartialWrite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/tenants/{tenant_id}/schemas/partial-write`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PartialWriteBodyToJSON(requestParameters['body']),
        };
    }

    /**
     * partially update your authorization model
     */
    async schemasPartialWriteRaw(requestParameters: SchemasPartialWriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaPartialWriteResponse>> {
        const requestOptions = await this.schemasPartialWriteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaPartialWriteResponseFromJSON(jsonValue));
    }

    /**
     * partially update your authorization model
     */
    async schemasPartialWrite(requestParameters: SchemasPartialWriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaPartialWriteResponse> {
        const response = await this.schemasPartialWriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for schemasRead without sending the request
     */
    async schemasReadRequestOpts(requestParameters: SchemasReadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling schemasRead().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling schemasRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/tenants/{tenant_id}/schemas/read`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SchemaReadBodyToJSON(requestParameters['body']),
        };
    }

    /**
     * read schema
     */
    async schemasReadRaw(requestParameters: SchemasReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaReadResponse>> {
        const requestOptions = await this.schemasReadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaReadResponseFromJSON(jsonValue));
    }

    /**
     * read schema
     */
    async schemasRead(requestParameters: SchemasReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaReadResponse> {
        const response = await this.schemasReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for schemasWrite without sending the request
     */
    async schemasWriteRequestOpts(requestParameters: SchemasWriteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling schemasWrite().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling schemasWrite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/tenants/{tenant_id}/schemas/write`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SchemaWriteBodyToJSON(requestParameters['body']),
        };
    }

    /**
     * write schema
     */
    async schemasWriteRaw(requestParameters: SchemasWriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaWriteResponse>> {
        const requestOptions = await this.schemasWriteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaWriteResponseFromJSON(jsonValue));
    }

    /**
     * write schema
     */
    async schemasWrite(requestParameters: SchemasWriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaWriteResponse> {
        const response = await this.schemasWriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
