/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Status,
  StreamResultOfWatchResponse,
  WatchBody,
} from '../models/index';
import {
    StatusFromJSON,
    StatusToJSON,
    StreamResultOfWatchResponseFromJSON,
    StreamResultOfWatchResponseToJSON,
    WatchBodyFromJSON,
    WatchBodyToJSON,
} from '../models/index';

export interface WatchWatchRequest {
    tenantId: string;
    body: WatchBody;
}

/**
 * 
 */
export class WatchApi extends runtime.BaseAPI {

    /**
     * Creates request options for watchWatch without sending the request
     */
    async watchWatchRequestOpts(requestParameters: WatchWatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling watchWatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling watchWatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/tenants/{tenant_id}/watch`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WatchBodyToJSON(requestParameters['body']),
        };
    }

    /**
     * watch changes
     */
    async watchWatchRaw(requestParameters: WatchWatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreamResultOfWatchResponse>> {
        const requestOptions = await this.watchWatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreamResultOfWatchResponseFromJSON(jsonValue));
    }

    /**
     * watch changes
     */
    async watchWatch(requestParameters: WatchWatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreamResultOfWatchResponse> {
        const response = await this.watchWatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
