/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityFilter } from './EntityFilter';
import {
    EntityFilterFromJSON,
    EntityFilterFromJSONTyped,
    EntityFilterToJSON,
} from './EntityFilter';

/**
 * AttributeFilter is used to filter attributes based on the entity and attribute names.
 * @export
 * @interface AttributeFilter
 */
export interface AttributeFilter {
    /**
     * 
     * @type {EntityFilter}
     * @memberof AttributeFilter
     */
    entity?: EntityFilter;
    /**
     * 
     * @type {Array<string>}
     * @memberof AttributeFilter
     */
    attributes?: Array<string>;
}

/**
 * Check if a given object implements the AttributeFilter interface.
 */
export function instanceOfAttributeFilter(value: object): value is AttributeFilter {
    return true;
}

export function AttributeFilterFromJSON(json: any): AttributeFilter {
    return AttributeFilterFromJSONTyped(json, false);
}

export function AttributeFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'entity': json['entity'] == null ? undefined : EntityFilterFromJSON(json['entity']),
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
    };
}

export function AttributeFilterToJSON(value?: AttributeFilter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'entity': EntityFilterToJSON(value['entity']),
        'attributes': value['attributes'],
    };
}

