/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { PermissionBulkCheckRequestItem } from './PermissionBulkCheckRequestItem';
import {
    PermissionBulkCheckRequestItemFromJSON,
    PermissionBulkCheckRequestItemFromJSONTyped,
    PermissionBulkCheckRequestItemToJSON,
    PermissionBulkCheckRequestItemToJSONTyped,
} from './PermissionBulkCheckRequestItem';
import type { PermissionCheckRequestMetadata } from './PermissionCheckRequestMetadata';
import {
    PermissionCheckRequestMetadataFromJSON,
    PermissionCheckRequestMetadataFromJSONTyped,
    PermissionCheckRequestMetadataToJSON,
    PermissionCheckRequestMetadataToJSONTyped,
} from './PermissionCheckRequestMetadata';
import type { Argument } from './Argument';
import {
    ArgumentFromJSON,
    ArgumentFromJSONTyped,
    ArgumentToJSON,
    ArgumentToJSONTyped,
} from './Argument';

/**
 * PermissionBulkCheckRequest is the request message for the BulkCheck method in the Permission service.
 * @export
 * @interface BulkCheckBody
 */
export interface BulkCheckBody {
    /**
     * 
     * @type {PermissionCheckRequestMetadata}
     * @memberof BulkCheckBody
     */
    metadata?: PermissionCheckRequestMetadata;
    /**
     * List of permission check requests, maximum 100 items.
     * @type {Array<PermissionBulkCheckRequestItem>}
     * @memberof BulkCheckBody
     */
    items?: Array<PermissionBulkCheckRequestItem>;
    /**
     * 
     * @type {Context}
     * @memberof BulkCheckBody
     */
    context?: Context;
    /**
     * Additional arguments associated with this request.
     * @type {Array<Argument>}
     * @memberof BulkCheckBody
     */
    arguments?: Array<Argument>;
}

/**
 * Check if a given object implements the BulkCheckBody interface.
 */
export function instanceOfBulkCheckBody(value: object): value is BulkCheckBody {
    return true;
}

export function BulkCheckBodyFromJSON(json: any): BulkCheckBody {
    return BulkCheckBodyFromJSONTyped(json, false);
}

export function BulkCheckBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkCheckBody {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : PermissionCheckRequestMetadataFromJSON(json['metadata']),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(PermissionBulkCheckRequestItemFromJSON)),
        'context': json['context'] == null ? undefined : ContextFromJSON(json['context']),
        'arguments': json['arguments'] == null ? undefined : ((json['arguments'] as Array<any>).map(ArgumentFromJSON)),
    };
}

export function BulkCheckBodyToJSON(json: any): BulkCheckBody {
    return BulkCheckBodyToJSONTyped(json, false);
}

export function BulkCheckBodyToJSONTyped(value?: BulkCheckBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': PermissionCheckRequestMetadataToJSON(value['metadata']),
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(PermissionBulkCheckRequestItemToJSON)),
        'context': ContextToJSON(value['context']),
        'arguments': value['arguments'] == null ? undefined : ((value['arguments'] as Array<any>).map(ArgumentToJSON)),
    };
}

