/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataBundle } from './DataBundle';
import {
    DataBundleFromJSON,
    DataBundleFromJSONTyped,
    DataBundleToJSON,
    DataBundleToJSONTyped,
} from './DataBundle';

/**
 * BundleWriteRequest is used to request the writing of a bundle.
 * It contains the tenant_id to identify the tenant and the Bundles object.
 * @export
 * @interface BundleWriteBody
 */
export interface BundleWriteBody {
    /**
     * Contains the bundle data to be written.
     * @type {Array<DataBundle>}
     * @memberof BundleWriteBody
     */
    bundles?: Array<DataBundle>;
}

/**
 * Check if a given object implements the BundleWriteBody interface.
 */
export function instanceOfBundleWriteBody(value: object): value is BundleWriteBody {
    return true;
}

export function BundleWriteBodyFromJSON(json: any): BundleWriteBody {
    return BundleWriteBodyFromJSONTyped(json, false);
}

export function BundleWriteBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleWriteBody {
    if (json == null) {
        return json;
    }
    return {
        
        'bundles': json['bundles'] == null ? undefined : ((json['bundles'] as Array<any>).map(DataBundleFromJSON)),
    };
}

export function BundleWriteBodyToJSON(json: any): BundleWriteBody {
    return BundleWriteBodyToJSONTyped(json, false);
}

export function BundleWriteBodyToJSONTyped(value?: BundleWriteBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bundles': value['bundles'] == null ? undefined : ((value['bundles'] as Array<any>).map(DataBundleToJSON)),
    };
}

