/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * BundleDeleteRequest is used to request the deletion of a bundle.
 * It contains the tenant_id to specify the tenant and the name of the bundle to be deleted.
 * @export
 * @interface BundleDeleteBody
 */
export interface BundleDeleteBody {
    /**
     * Name of the bundle to be deleted.
     * @type {string}
     * @memberof BundleDeleteBody
     */
    name?: string;
}

/**
 * Check if a given object implements the BundleDeleteBody interface.
 */
export function instanceOfBundleDeleteBody(value: object): value is BundleDeleteBody {
    return true;
}

export function BundleDeleteBodyFromJSON(json: any): BundleDeleteBody {
    return BundleDeleteBodyFromJSONTyped(json, false);
}

export function BundleDeleteBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleDeleteBody {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function BundleDeleteBodyToJSON(json: any): BundleDeleteBody {
    return BundleDeleteBodyToJSONTyped(json, false);
}

export function BundleDeleteBodyToJSONTyped(value?: BundleDeleteBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

