/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * BundleDeleteRequest is used to request the deletion of a bundle.
 * It contains the tenant_id to specify the tenant and the name of the bundle to be deleted.
 * @export
 * @interface BundleDeleteRequest
 */
export interface BundleDeleteRequest {
    /**
     * Name of the bundle to be deleted.
     * @type {string}
     * @memberof BundleDeleteRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the BundleDeleteRequest interface.
 */
export function instanceOfBundleDeleteRequest(value: object): value is BundleDeleteRequest {
    return true;
}

export function BundleDeleteRequestFromJSON(json: any): BundleDeleteRequest {
    return BundleDeleteRequestFromJSONTyped(json, false);
}

export function BundleDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function BundleDeleteRequestToJSON(value?: BundleDeleteRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

