/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BundleDeleteResponse
 */
export interface BundleDeleteResponse {
    /**
     * 
     * @type {string}
     * @memberof BundleDeleteResponse
     */
    name?: string;
}

/**
 * Check if a given object implements the BundleDeleteResponse interface.
 */
export function instanceOfBundleDeleteResponse(value: object): value is BundleDeleteResponse {
    return true;
}

export function BundleDeleteResponseFromJSON(json: any): BundleDeleteResponse {
    return BundleDeleteResponseFromJSONTyped(json, false);
}

export function BundleDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function BundleDeleteResponseToJSON(value?: BundleDeleteResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

