/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataBundle } from './DataBundle';
import {
    DataBundleFromJSON,
    DataBundleFromJSONTyped,
    DataBundleToJSON,
} from './DataBundle';

/**
 * 
 * @export
 * @interface BundleReadResponse
 */
export interface BundleReadResponse {
    /**
     * 
     * @type {DataBundle}
     * @memberof BundleReadResponse
     */
    bundle?: DataBundle;
}

/**
 * Check if a given object implements the BundleReadResponse interface.
 */
export function instanceOfBundleReadResponse(value: object): value is BundleReadResponse {
    return true;
}

export function BundleReadResponseFromJSON(json: any): BundleReadResponse {
    return BundleReadResponseFromJSONTyped(json, false);
}

export function BundleReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleReadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bundle': json['bundle'] == null ? undefined : DataBundleFromJSON(json['bundle']),
    };
}

export function BundleReadResponseToJSON(value?: BundleReadResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bundle': DataBundleToJSON(value['bundle']),
    };
}

