/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { PermissionCheckRequestMetadata } from './PermissionCheckRequestMetadata';
import {
    PermissionCheckRequestMetadataFromJSON,
    PermissionCheckRequestMetadataFromJSONTyped,
    PermissionCheckRequestMetadataToJSON,
    PermissionCheckRequestMetadataToJSONTyped,
} from './PermissionCheckRequestMetadata';
import type { Entity } from './Entity';
import {
    EntityFromJSON,
    EntityFromJSONTyped,
    EntityToJSON,
    EntityToJSONTyped,
} from './Entity';
import type { Argument } from './Argument';
import {
    ArgumentFromJSON,
    ArgumentFromJSONTyped,
    ArgumentToJSON,
    ArgumentToJSONTyped,
} from './Argument';
import type { Subject } from './Subject';
import {
    SubjectFromJSON,
    SubjectFromJSONTyped,
    SubjectToJSON,
    SubjectToJSONTyped,
} from './Subject';

/**
 * PermissionCheckRequest is the request message for the Check method in the Permission service.
 * @export
 * @interface CheckBody
 */
export interface CheckBody {
    /**
     * 
     * @type {PermissionCheckRequestMetadata}
     * @memberof CheckBody
     */
    metadata?: PermissionCheckRequestMetadata;
    /**
     * 
     * @type {Entity}
     * @memberof CheckBody
     */
    entity?: Entity;
    /**
     * The action the user wants to perform on the resource
     * @type {string}
     * @memberof CheckBody
     */
    permission?: string;
    /**
     * 
     * @type {Subject}
     * @memberof CheckBody
     */
    subject?: Subject;
    /**
     * 
     * @type {Context}
     * @memberof CheckBody
     */
    context?: Context;
    /**
     * Additional arguments associated with this request.
     * @type {Array<Argument>}
     * @memberof CheckBody
     */
    arguments?: Array<Argument>;
}

/**
 * Check if a given object implements the CheckBody interface.
 */
export function instanceOfCheckBody(value: object): value is CheckBody {
    return true;
}

export function CheckBodyFromJSON(json: any): CheckBody {
    return CheckBodyFromJSONTyped(json, false);
}

export function CheckBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckBody {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : PermissionCheckRequestMetadataFromJSON(json['metadata']),
        'entity': json['entity'] == null ? undefined : EntityFromJSON(json['entity']),
        'permission': json['permission'] == null ? undefined : json['permission'],
        'subject': json['subject'] == null ? undefined : SubjectFromJSON(json['subject']),
        'context': json['context'] == null ? undefined : ContextFromJSON(json['context']),
        'arguments': json['arguments'] == null ? undefined : ((json['arguments'] as Array<any>).map(ArgumentFromJSON)),
    };
}

export function CheckBodyToJSON(json: any): CheckBody {
    return CheckBodyToJSONTyped(json, false);
}

export function CheckBodyToJSONTyped(value?: CheckBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': PermissionCheckRequestMetadataToJSON(value['metadata']),
        'entity': EntityToJSON(value['entity']),
        'permission': value['permission'],
        'subject': SubjectToJSON(value['subject']),
        'context': ContextToJSON(value['context']),
        'arguments': value['arguments'] == null ? undefined : ((value['arguments'] as Array<any>).map(ArgumentToJSON)),
    };
}

