/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * CEL component specifier.
 * 
 *  - COMPONENT_PARSER: Parser. Converts a CEL string to an AST.
 *  - COMPONENT_TYPE_CHECKER: Type checker. Checks that references in an AST are defined and types
 * agree.
 *  - COMPONENT_RUNTIME: Runtime. Evaluates a parsed and optionally checked CEL AST against a
 * context.
 * @export
 */
export const Component = {
    Parser: 'COMPONENT_PARSER',
    TypeChecker: 'COMPONENT_TYPE_CHECKER',
    Runtime: 'COMPONENT_RUNTIME'
} as const;
export type Component = typeof Component[keyof typeof Component];


export function instanceOfComponent(value: any): boolean {
    for (const key in Component) {
        if (Object.prototype.hasOwnProperty.call(Component, key)) {
            if (Component[key as keyof typeof Component] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ComponentFromJSON(json: any): Component {
    return ComponentFromJSONTyped(json, false);
}

export function ComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Component {
    return json as Component;
}

export function ComponentToJSON(value?: Component | null): any {
    return value as any;
}

export function ComponentToJSONTyped(value: any, ignoreDiscriminator: boolean): Component {
    return value as Component;
}

