/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ContextAttribute defines a context attribute which includes its name.
 * @export
 * @interface ContextAttribute
 */
export interface ContextAttribute {
    /**
     * 
     * @type {string}
     * @memberof ContextAttribute
     */
    name?: string;
}

/**
 * Check if a given object implements the ContextAttribute interface.
 */
export function instanceOfContextAttribute(value: object): value is ContextAttribute {
    return true;
}

export function ContextAttributeFromJSON(json: any): ContextAttribute {
    return ContextAttributeFromJSONTyped(json, false);
}

export function ContextAttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContextAttribute {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ContextAttributeToJSON(value?: ContextAttribute | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

