/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *  - OPERATION_UNSPECIFIED: Default operation, not specified.
 *  - OPERATION_CREATE: Creation operation.
 *  - OPERATION_DELETE: Deletion operation.
 * @export
 */
export const DataChangeOperation = {
    Unspecified: 'OPERATION_UNSPECIFIED',
    Create: 'OPERATION_CREATE',
    Delete: 'OPERATION_DELETE'
} as const;
export type DataChangeOperation = typeof DataChangeOperation[keyof typeof DataChangeOperation];


export function instanceOfDataChangeOperation(value: any): boolean {
    for (const key in DataChangeOperation) {
        if (Object.prototype.hasOwnProperty.call(DataChangeOperation, key)) {
            if ((DataChangeOperation as Record<string, DataChangeOperation>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DataChangeOperationFromJSON(json: any): DataChangeOperation {
    return DataChangeOperationFromJSONTyped(json, false);
}

export function DataChangeOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataChangeOperation {
    return json as DataChangeOperation;
}

export function DataChangeOperationToJSON(value?: DataChangeOperation | null): any {
    return value as any;
}

