/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributeFilter } from './AttributeFilter';
import {
    AttributeFilterFromJSON,
    AttributeFilterFromJSONTyped,
    AttributeFilterToJSON,
} from './AttributeFilter';
import type { TupleFilter } from './TupleFilter';
import {
    TupleFilterFromJSON,
    TupleFilterFromJSONTyped,
    TupleFilterToJSON,
} from './TupleFilter';

/**
 * DataDeleteRequest defines the structure of a request to delete data.
 * It includes the tenant_id and filters for selecting tuples and attributes to be deleted.
 * @export
 * @interface DataDeleteRequest
 */
export interface DataDeleteRequest {
    /**
     * 
     * @type {TupleFilter}
     * @memberof DataDeleteRequest
     */
    tupleFilter?: TupleFilter;
    /**
     * 
     * @type {AttributeFilter}
     * @memberof DataDeleteRequest
     */
    attributeFilter?: AttributeFilter;
}

/**
 * Check if a given object implements the DataDeleteRequest interface.
 */
export function instanceOfDataDeleteRequest(value: object): value is DataDeleteRequest {
    return true;
}

export function DataDeleteRequestFromJSON(json: any): DataDeleteRequest {
    return DataDeleteRequestFromJSONTyped(json, false);
}

export function DataDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tupleFilter': json['tuple_filter'] == null ? undefined : TupleFilterFromJSON(json['tuple_filter']),
        'attributeFilter': json['attribute_filter'] == null ? undefined : AttributeFilterFromJSON(json['attribute_filter']),
    };
}

export function DataDeleteRequestToJSON(value?: DataDeleteRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tuple_filter': TupleFilterToJSON(value['tupleFilter']),
        'attribute_filter': AttributeFilterToJSON(value['attributeFilter']),
    };
}

