/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * DataDeleteResponse defines the structure of the response to a data delete request.
 * It includes a snap_token representing the state of the database after the deletion.
 * @export
 * @interface DataDeleteResponse
 */
export interface DataDeleteResponse {
    /**
     * The snap token to avoid stale cache, see more details on [Snap Tokens](../../operations/snap-tokens)
     * @type {string}
     * @memberof DataDeleteResponse
     */
    snapToken?: string;
}

/**
 * Check if a given object implements the DataDeleteResponse interface.
 */
export function instanceOfDataDeleteResponse(value: object): value is DataDeleteResponse {
    return true;
}

export function DataDeleteResponseFromJSON(json: any): DataDeleteResponse {
    return DataDeleteResponseFromJSONTyped(json, false);
}

export function DataDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'snapToken': json['snap_token'] == null ? undefined : json['snap_token'],
    };
}

export function DataDeleteResponseToJSON(value?: DataDeleteResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'snap_token': value['snapToken'],
    };
}

