/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributeReadRequestMetadata } from './AttributeReadRequestMetadata';
import {
    AttributeReadRequestMetadataFromJSON,
    AttributeReadRequestMetadataFromJSONTyped,
    AttributeReadRequestMetadataToJSON,
} from './AttributeReadRequestMetadata';
import type { AttributeFilter } from './AttributeFilter';
import {
    AttributeFilterFromJSON,
    AttributeFilterFromJSONTyped,
    AttributeFilterToJSON,
} from './AttributeFilter';

/**
 * AttributeReadRequest defines the structure of a request for reading attributes.
 * It includes the tenant_id, metadata, attribute filter, page size for pagination, and a continuous token for multi-page results.
 * @export
 * @interface DataAttributesReadRequest
 */
export interface DataAttributesReadRequest {
    /**
     * 
     * @type {AttributeReadRequestMetadata}
     * @memberof DataAttributesReadRequest
     */
    metadata?: AttributeReadRequestMetadata;
    /**
     * 
     * @type {AttributeFilter}
     * @memberof DataAttributesReadRequest
     */
    filter?: AttributeFilter;
    /**
     * page_size specifies the number of results to return in a single page.
     * If more results are available, a continuous_token is included in the response.
     * @type {number}
     * @memberof DataAttributesReadRequest
     */
    pageSize?: number;
    /**
     * continuous_token is used in case of paginated reads to get the next page of results.
     * @type {string}
     * @memberof DataAttributesReadRequest
     */
    continuousToken?: string;
}

/**
 * Check if a given object implements the DataAttributesReadRequest interface.
 */
export function instanceOfDataAttributesReadRequest(value: object): value is DataAttributesReadRequest {
    return true;
}

export function DataAttributesReadRequestFromJSON(json: any): DataAttributesReadRequest {
    return DataAttributesReadRequestFromJSONTyped(json, false);
}

export function DataAttributesReadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataAttributesReadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : AttributeReadRequestMetadataFromJSON(json['metadata']),
        'filter': json['filter'] == null ? undefined : AttributeFilterFromJSON(json['filter']),
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'continuousToken': json['continuous_token'] == null ? undefined : json['continuous_token'],
    };
}

export function DataAttributesReadRequestToJSON(value?: DataAttributesReadRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metadata': AttributeReadRequestMetadataToJSON(value['metadata']),
        'filter': AttributeFilterToJSON(value['filter']),
        'page_size': value['pageSize'],
        'continuous_token': value['continuousToken'],
    };
}

