/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributeFilter } from './AttributeFilter';
import {
    AttributeFilterFromJSON,
    AttributeFilterFromJSONTyped,
    AttributeFilterToJSON,
    AttributeFilterToJSONTyped,
} from './AttributeFilter';
import type { TupleFilter } from './TupleFilter';
import {
    TupleFilterFromJSON,
    TupleFilterFromJSONTyped,
    TupleFilterToJSON,
    TupleFilterToJSONTyped,
} from './TupleFilter';

/**
 * DataDeleteRequest defines the structure of a request to delete data.
 * It includes the tenant_id and filters for selecting tuples and attributes to be deleted.
 * @export
 * @interface DataDeleteBody
 */
export interface DataDeleteBody {
    /**
     * 
     * @type {TupleFilter}
     * @memberof DataDeleteBody
     */
    tupleFilter?: TupleFilter;
    /**
     * 
     * @type {AttributeFilter}
     * @memberof DataDeleteBody
     */
    attributeFilter?: AttributeFilter;
}

/**
 * Check if a given object implements the DataDeleteBody interface.
 */
export function instanceOfDataDeleteBody(value: object): value is DataDeleteBody {
    return true;
}

export function DataDeleteBodyFromJSON(json: any): DataDeleteBody {
    return DataDeleteBodyFromJSONTyped(json, false);
}

export function DataDeleteBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataDeleteBody {
    if (json == null) {
        return json;
    }
    return {
        
        'tupleFilter': json['tuple_filter'] == null ? undefined : TupleFilterFromJSON(json['tuple_filter']),
        'attributeFilter': json['attribute_filter'] == null ? undefined : AttributeFilterFromJSON(json['attribute_filter']),
    };
}

export function DataDeleteBodyToJSON(json: any): DataDeleteBody {
    return DataDeleteBodyToJSONTyped(json, false);
}

export function DataDeleteBodyToJSONTyped(value?: DataDeleteBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tuple_filter': TupleFilterToJSON(value['tupleFilter']),
        'attribute_filter': AttributeFilterToJSON(value['attributeFilter']),
    };
}

