/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelationshipReadRequestMetadata } from './RelationshipReadRequestMetadata';
import {
    RelationshipReadRequestMetadataFromJSON,
    RelationshipReadRequestMetadataFromJSONTyped,
    RelationshipReadRequestMetadataToJSON,
} from './RelationshipReadRequestMetadata';
import type { TupleFilter } from './TupleFilter';
import {
    TupleFilterFromJSON,
    TupleFilterFromJSONTyped,
    TupleFilterToJSON,
} from './TupleFilter';

/**
 * RelationshipReadRequest defines the structure of a request for reading relationships.
 * It contains the necessary information such as tenant_id, metadata, and filter for the read operation.
 * @export
 * @interface DataRelationshipsReadRequest
 */
export interface DataRelationshipsReadRequest {
    /**
     * 
     * @type {RelationshipReadRequestMetadata}
     * @memberof DataRelationshipsReadRequest
     */
    metadata?: RelationshipReadRequestMetadata;
    /**
     * 
     * @type {TupleFilter}
     * @memberof DataRelationshipsReadRequest
     */
    filter?: TupleFilter;
    /**
     * page_size specifies the number of results to return in a single page.
     * If more results are available, a continuous_token is included in the response.
     * @type {number}
     * @memberof DataRelationshipsReadRequest
     */
    pageSize?: number;
    /**
     * continuous_token is used in case of paginated reads to get the next page of results.
     * @type {string}
     * @memberof DataRelationshipsReadRequest
     */
    continuousToken?: string;
}

/**
 * Check if a given object implements the DataRelationshipsReadRequest interface.
 */
export function instanceOfDataRelationshipsReadRequest(value: object): value is DataRelationshipsReadRequest {
    return true;
}

export function DataRelationshipsReadRequestFromJSON(json: any): DataRelationshipsReadRequest {
    return DataRelationshipsReadRequestFromJSONTyped(json, false);
}

export function DataRelationshipsReadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataRelationshipsReadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : RelationshipReadRequestMetadataFromJSON(json['metadata']),
        'filter': json['filter'] == null ? undefined : TupleFilterFromJSON(json['filter']),
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'continuousToken': json['continuous_token'] == null ? undefined : json['continuous_token'],
    };
}

export function DataRelationshipsReadRequestToJSON(value?: DataRelationshipsReadRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metadata': RelationshipReadRequestMetadataToJSON(value['metadata']),
        'filter': TupleFilterToJSON(value['filter']),
        'page_size': value['pageSize'],
        'continuous_token': value['continuousToken'],
    };
}

