/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TupleFilter } from './TupleFilter';
import {
    TupleFilterFromJSON,
    TupleFilterFromJSONTyped,
    TupleFilterToJSON,
    TupleFilterToJSONTyped,
} from './TupleFilter';

/**
 * 
 * @export
 * @interface DeleteRelationshipsBody
 */
export interface DeleteRelationshipsBody {
    /**
     * 
     * @type {TupleFilter}
     * @memberof DeleteRelationshipsBody
     */
    filter?: TupleFilter;
}

/**
 * Check if a given object implements the DeleteRelationshipsBody interface.
 */
export function instanceOfDeleteRelationshipsBody(value: object): value is DeleteRelationshipsBody {
    return true;
}

export function DeleteRelationshipsBodyFromJSON(json: any): DeleteRelationshipsBody {
    return DeleteRelationshipsBodyFromJSONTyped(json, false);
}

export function DeleteRelationshipsBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteRelationshipsBody {
    if (json == null) {
        return json;
    }
    return {
        
        'filter': json['filter'] == null ? undefined : TupleFilterFromJSON(json['filter']),
    };
}

export function DeleteRelationshipsBodyToJSON(json: any): DeleteRelationshipsBody {
    return DeleteRelationshipsBodyToJSONTyped(json, false);
}

export function DeleteRelationshipsBodyToJSONTyped(value?: DeleteRelationshipsBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filter': TupleFilterToJSON(value['filter']),
    };
}

