/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * EntityFilter is used to filter entities based on the type and ids.
 * @export
 * @interface EntityFilter
 */
export interface EntityFilter {
    /**
     * 
     * @type {string}
     * @memberof EntityFilter
     */
    type?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EntityFilter
     */
    ids?: Array<string>;
}

/**
 * Check if a given object implements the EntityFilter interface.
 */
export function instanceOfEntityFilter(value: object): value is EntityFilter {
    return true;
}

export function EntityFilterFromJSON(json: any): EntityFilter {
    return EntityFilterFromJSONTyped(json, false);
}

export function EntityFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'ids': json['ids'] == null ? undefined : json['ids'],
    };
}

export function EntityFilterToJSON(value?: EntityFilter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'ids': value['ids'],
    };
}

