/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The Reference enum specifies whether a name pertains to a relation, permission, or attribute.
 * 
 *  - REFERENCE_UNSPECIFIED: Default, unspecified reference.
 *  - REFERENCE_RELATION: Indicates that the name refers to a relation.
 *  - REFERENCE_PERMISSION: Indicates that the name refers to a permission.
 *  - REFERENCE_ATTRIBUTE: Indicates that the name refers to an attribute.
 * @export
 */
export const EntityDefinitionReference = {
    Unspecified: 'REFERENCE_UNSPECIFIED',
    Relation: 'REFERENCE_RELATION',
    Permission: 'REFERENCE_PERMISSION',
    Attribute: 'REFERENCE_ATTRIBUTE'
} as const;
export type EntityDefinitionReference = typeof EntityDefinitionReference[keyof typeof EntityDefinitionReference];


export function instanceOfEntityDefinitionReference(value: any): boolean {
    for (const key in EntityDefinitionReference) {
        if (Object.prototype.hasOwnProperty.call(EntityDefinitionReference, key)) {
            if ((EntityDefinitionReference as Record<string, EntityDefinitionReference>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EntityDefinitionReferenceFromJSON(json: any): EntityDefinitionReference {
    return EntityDefinitionReferenceFromJSONTyped(json, false);
}

export function EntityDefinitionReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityDefinitionReference {
    return json as EntityDefinitionReference;
}

export function EntityDefinitionReferenceToJSON(value?: EntityDefinitionReference | null): any {
    return value as any;
}

