/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Expand } from './V1Expand';
import {
    V1ExpandFromJSON,
    V1ExpandFromJSONTyped,
    V1ExpandToJSON,
    V1ExpandToJSONTyped,
} from './V1Expand';
import type { ExpandTreeNodeOperation } from './ExpandTreeNodeOperation';
import {
    ExpandTreeNodeOperationFromJSON,
    ExpandTreeNodeOperationFromJSONTyped,
    ExpandTreeNodeOperationToJSON,
    ExpandTreeNodeOperationToJSONTyped,
} from './ExpandTreeNodeOperation';

/**
 * ExpandTreeNode represents a node in an expansion tree with a specific operation and its children.
 * @export
 * @interface ExpandTreeNode
 */
export interface ExpandTreeNode {
    /**
     * 
     * @type {ExpandTreeNodeOperation}
     * @memberof ExpandTreeNode
     */
    operation?: ExpandTreeNodeOperation;
    /**
     * 
     * @type {Array<V1Expand>}
     * @memberof ExpandTreeNode
     */
    children?: Array<V1Expand>;
}



/**
 * Check if a given object implements the ExpandTreeNode interface.
 */
export function instanceOfExpandTreeNode(value: object): value is ExpandTreeNode {
    return true;
}

export function ExpandTreeNodeFromJSON(json: any): ExpandTreeNode {
    return ExpandTreeNodeFromJSONTyped(json, false);
}

export function ExpandTreeNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpandTreeNode {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['operation'] == null ? undefined : ExpandTreeNodeOperationFromJSON(json['operation']),
        'children': json['children'] == null ? undefined : ((json['children'] as Array<any>).map(V1ExpandFromJSON)),
    };
}

export function ExpandTreeNodeToJSON(json: any): ExpandTreeNode {
    return ExpandTreeNodeToJSONTyped(json, false);
}

export function ExpandTreeNodeToJSONTyped(value?: ExpandTreeNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation': ExpandTreeNodeOperationToJSON(value['operation']),
        'children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(V1ExpandToJSON)),
    };
}

