/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An identifier expression. e.g. `request`.
 * @export
 * @interface Ident
 */
export interface Ident {
    /**
     * Required. Holds a single, unqualified identifier, possibly preceded by a
     * '.'.
     * 
     * Qualified names are represented by the [Expr.Select][google.api.expr.v1alpha1.Expr.Select] expression.
     * @type {string}
     * @memberof Ident
     */
    name?: string;
}

/**
 * Check if a given object implements the Ident interface.
 */
export function instanceOfIdent(value: object): value is Ident {
    return true;
}

export function IdentFromJSON(json: any): Ident {
    return IdentFromJSONTyped(json, false);
}

export function IdentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ident {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function IdentToJSON(value?: Ident | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

