/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1alpha1Type } from './V1alpha1Type';
import {
    V1alpha1TypeFromJSON,
    V1alpha1TypeFromJSONTyped,
    V1alpha1TypeToJSON,
} from './V1alpha1Type';

/**
 * List type with typed elements, e.g. `list<example.proto.MyMessage>`.
 * @export
 * @interface ListType
 */
export interface ListType {
    /**
     * 
     * @type {V1alpha1Type}
     * @memberof ListType
     */
    elemType?: V1alpha1Type;
}

/**
 * Check if a given object implements the ListType interface.
 */
export function instanceOfListType(value: object): value is ListType {
    return true;
}

export function ListTypeFromJSON(json: any): ListType {
    return ListTypeFromJSONTyped(json, false);
}

export function ListTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListType {
    if (json == null) {
        return json;
    }
    return {
        
        'elemType': json['elemType'] == null ? undefined : V1alpha1TypeFromJSON(json['elemType']),
    };
}

export function ListTypeToJSON(value?: ListType | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'elemType': V1alpha1TypeToJSON(value['elemType']),
    };
}

