/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { PermissionLookupEntityRequestMetadata } from './PermissionLookupEntityRequestMetadata';
import {
    PermissionLookupEntityRequestMetadataFromJSON,
    PermissionLookupEntityRequestMetadataFromJSONTyped,
    PermissionLookupEntityRequestMetadataToJSON,
    PermissionLookupEntityRequestMetadataToJSONTyped,
} from './PermissionLookupEntityRequestMetadata';
import type { StringArrayValue } from './StringArrayValue';
import {
    StringArrayValueFromJSON,
    StringArrayValueFromJSONTyped,
    StringArrayValueToJSON,
    StringArrayValueToJSONTyped,
} from './StringArrayValue';
import type { Subject } from './Subject';
import {
    SubjectFromJSON,
    SubjectFromJSONTyped,
    SubjectToJSON,
    SubjectToJSONTyped,
} from './Subject';

/**
 * PermissionLookupEntityRequest is the request message for the LookupEntity method in the Permission service.
 * @export
 * @interface LookupEntityBody
 */
export interface LookupEntityBody {
    /**
     * 
     * @type {PermissionLookupEntityRequestMetadata}
     * @memberof LookupEntityBody
     */
    metadata?: PermissionLookupEntityRequestMetadata;
    /**
     * Type of the entity to lookup, required, must start with a letter and can include alphanumeric and underscore, max 64 bytes.
     * @type {string}
     * @memberof LookupEntityBody
     */
    entityType?: string;
    /**
     * Name of the permission to check, required, must start with a letter and can include alphanumeric and underscore, max 64 bytes.
     * @type {string}
     * @memberof LookupEntityBody
     */
    permission?: string;
    /**
     * 
     * @type {Subject}
     * @memberof LookupEntityBody
     */
    subject?: Subject;
    /**
     * 
     * @type {Context}
     * @memberof LookupEntityBody
     */
    context?: Context;
    /**
     * Scope: A map that associates entity types with lists of identifiers. Each entry
     * helps filter requests by specifying which entities are relevant to the operation.
     * @type {{ [key: string]: StringArrayValue; }}
     * @memberof LookupEntityBody
     */
    scope?: { [key: string]: StringArrayValue; };
    /**
     * page_size is the number of entities to be returned in the response.
     * The value should be between 1 and 100.
     * @type {number}
     * @memberof LookupEntityBody
     */
    pageSize?: number;
    /**
     * continuous_token is an optional parameter used for pagination.
     * It should be the value received in the previous response.
     * @type {string}
     * @memberof LookupEntityBody
     */
    continuousToken?: string;
}

/**
 * Check if a given object implements the LookupEntityBody interface.
 */
export function instanceOfLookupEntityBody(value: object): value is LookupEntityBody {
    return true;
}

export function LookupEntityBodyFromJSON(json: any): LookupEntityBody {
    return LookupEntityBodyFromJSONTyped(json, false);
}

export function LookupEntityBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookupEntityBody {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : PermissionLookupEntityRequestMetadataFromJSON(json['metadata']),
        'entityType': json['entity_type'] == null ? undefined : json['entity_type'],
        'permission': json['permission'] == null ? undefined : json['permission'],
        'subject': json['subject'] == null ? undefined : SubjectFromJSON(json['subject']),
        'context': json['context'] == null ? undefined : ContextFromJSON(json['context']),
        'scope': json['scope'] == null ? undefined : (mapValues(json['scope'], StringArrayValueFromJSON)),
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'continuousToken': json['continuous_token'] == null ? undefined : json['continuous_token'],
    };
}

export function LookupEntityBodyToJSON(json: any): LookupEntityBody {
    return LookupEntityBodyToJSONTyped(json, false);
}

export function LookupEntityBodyToJSONTyped(value?: LookupEntityBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': PermissionLookupEntityRequestMetadataToJSON(value['metadata']),
        'entity_type': value['entityType'],
        'permission': value['permission'],
        'subject': SubjectToJSON(value['subject']),
        'context': ContextToJSON(value['context']),
        'scope': value['scope'] == null ? undefined : (mapValues(value['scope'], StringArrayValueToJSON)),
        'page_size': value['pageSize'],
        'continuous_token': value['continuousToken'],
    };
}

