/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * `NullValue` is a singleton enumeration to represent the null value for the
 * `Value` type union.
 * 
 * The JSON representation for `NullValue` is JSON `null`.
 * 
 *  - NULL_VALUE: Null value.
 * @export
 */
export const NullValue = {
    NullValue: 'NULL_VALUE'
} as const;
export type NullValue = typeof NullValue[keyof typeof NullValue];


export function instanceOfNullValue(value: any): boolean {
    for (const key in NullValue) {
        if (Object.prototype.hasOwnProperty.call(NullValue, key)) {
            if ((NullValue as Record<string, NullValue>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NullValueFromJSON(json: any): NullValue {
    return NullValueFromJSONTyped(json, false);
}

export function NullValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): NullValue {
    return json as NullValue;
}

export function NullValueToJSON(value?: NullValue | null): any {
    return value as any;
}

