/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SchemaPartialWriteRequestMetadata } from './SchemaPartialWriteRequestMetadata';
import {
    SchemaPartialWriteRequestMetadataFromJSON,
    SchemaPartialWriteRequestMetadataFromJSONTyped,
    SchemaPartialWriteRequestMetadataToJSON,
    SchemaPartialWriteRequestMetadataToJSONTyped,
} from './SchemaPartialWriteRequestMetadata';
import type { Partials } from './Partials';
import {
    PartialsFromJSON,
    PartialsFromJSONTyped,
    PartialsToJSON,
    PartialsToJSONTyped,
} from './Partials';

/**
 * 
 * @export
 * @interface PartialWriteBody
 */
export interface PartialWriteBody {
    /**
     * 
     * @type {SchemaPartialWriteRequestMetadata}
     * @memberof PartialWriteBody
     */
    metadata?: SchemaPartialWriteRequestMetadata;
    /**
     * 
     * @type {{ [key: string]: Partials; }}
     * @memberof PartialWriteBody
     */
    partials?: { [key: string]: Partials; };
}

/**
 * Check if a given object implements the PartialWriteBody interface.
 */
export function instanceOfPartialWriteBody(value: object): value is PartialWriteBody {
    return true;
}

export function PartialWriteBodyFromJSON(json: any): PartialWriteBody {
    return PartialWriteBodyFromJSONTyped(json, false);
}

export function PartialWriteBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartialWriteBody {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : SchemaPartialWriteRequestMetadataFromJSON(json['metadata']),
        'partials': json['partials'] == null ? undefined : (mapValues(json['partials'], PartialsFromJSON)),
    };
}

export function PartialWriteBodyToJSON(json: any): PartialWriteBody {
    return PartialWriteBodyToJSONTyped(json, false);
}

export function PartialWriteBodyToJSONTyped(value?: PartialWriteBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': SchemaPartialWriteRequestMetadataToJSON(value['metadata']),
        'partials': value['partials'] == null ? undefined : (mapValues(value['partials'], PartialsToJSON)),
    };
}

