/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Partials
 */
export interface Partials {
    /**
     * 
     * @type {Array<string>}
     * @memberof Partials
     */
    write?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Partials
     */
    _delete?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Partials
     */
    update?: Array<string>;
}

/**
 * Check if a given object implements the Partials interface.
 */
export function instanceOfPartials(value: object): value is Partials {
    return true;
}

export function PartialsFromJSON(json: any): Partials {
    return PartialsFromJSONTyped(json, false);
}

export function PartialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Partials {
    if (json == null) {
        return json;
    }
    return {
        
        'write': json['write'] == null ? undefined : json['write'],
        '_delete': json['delete'] == null ? undefined : json['delete'],
        'update': json['update'] == null ? undefined : json['update'],
    };
}

export function PartialsToJSON(value?: Partials | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'write': value['write'],
        'delete': value['_delete'],
        'update': value['update'],
    };
}

