/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PermissionSubjectPermissionRequestMetadata metadata for the PermissionSubjectPermissionRequest.
 * @export
 * @interface PermissionSubjectPermissionRequestMetadata
 */
export interface PermissionSubjectPermissionRequestMetadata {
    /**
     * Version of the schema.
     * @type {string}
     * @memberof PermissionSubjectPermissionRequestMetadata
     */
    schemaVersion?: string;
    /**
     * The snap token to avoid stale cache, see more details on [Snap Tokens](../../operations/snap-tokens).
     * @type {string}
     * @memberof PermissionSubjectPermissionRequestMetadata
     */
    snapToken?: string;
    /**
     * Whether to only check permissions.
     * @type {boolean}
     * @memberof PermissionSubjectPermissionRequestMetadata
     */
    onlyPermission?: boolean;
    /**
     * Query limit when if recursive database queries got in loop.
     * @type {number}
     * @memberof PermissionSubjectPermissionRequestMetadata
     */
    depth?: number;
}

/**
 * Check if a given object implements the PermissionSubjectPermissionRequestMetadata interface.
 */
export function instanceOfPermissionSubjectPermissionRequestMetadata(value: object): value is PermissionSubjectPermissionRequestMetadata {
    return true;
}

export function PermissionSubjectPermissionRequestMetadataFromJSON(json: any): PermissionSubjectPermissionRequestMetadata {
    return PermissionSubjectPermissionRequestMetadataFromJSONTyped(json, false);
}

export function PermissionSubjectPermissionRequestMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionSubjectPermissionRequestMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'] == null ? undefined : json['schema_version'],
        'snapToken': json['snap_token'] == null ? undefined : json['snap_token'],
        'onlyPermission': json['only_permission'] == null ? undefined : json['only_permission'],
        'depth': json['depth'] == null ? undefined : json['depth'],
    };
}

export function PermissionSubjectPermissionRequestMetadataToJSON(value?: PermissionSubjectPermissionRequestMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'schema_version': value['schemaVersion'],
        'snap_token': value['snapToken'],
        'only_permission': value['onlyPermission'],
        'depth': value['depth'],
    };
}

