/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionCheckResponse } from './PermissionCheckResponse';
import {
    PermissionCheckResponseFromJSON,
    PermissionCheckResponseFromJSONTyped,
    PermissionCheckResponseToJSON,
    PermissionCheckResponseToJSONTyped,
} from './PermissionCheckResponse';

/**
 * PermissionBulkCheckResponse is the response message for the BulkCheck method in the Permission service.
 * @export
 * @interface PermissionBulkCheckResponse
 */
export interface PermissionBulkCheckResponse {
    /**
     * List of permission check responses corresponding to each request.
     * @type {Array<PermissionCheckResponse>}
     * @memberof PermissionBulkCheckResponse
     */
    results?: Array<PermissionCheckResponse>;
}

/**
 * Check if a given object implements the PermissionBulkCheckResponse interface.
 */
export function instanceOfPermissionBulkCheckResponse(value: object): value is PermissionBulkCheckResponse {
    return true;
}

export function PermissionBulkCheckResponseFromJSON(json: any): PermissionBulkCheckResponse {
    return PermissionBulkCheckResponseFromJSONTyped(json, false);
}

export function PermissionBulkCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionBulkCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PermissionCheckResponseFromJSON)),
    };
}

export function PermissionBulkCheckResponseToJSON(json: any): PermissionBulkCheckResponse {
    return PermissionBulkCheckResponseToJSONTyped(json, false);
}

export function PermissionBulkCheckResponseToJSONTyped(value?: PermissionBulkCheckResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PermissionCheckResponseToJSON)),
    };
}

