/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionCheckResponseMetadata } from './PermissionCheckResponseMetadata';
import {
    PermissionCheckResponseMetadataFromJSON,
    PermissionCheckResponseMetadataFromJSONTyped,
    PermissionCheckResponseMetadataToJSON,
} from './PermissionCheckResponseMetadata';
import type { CheckResult } from './CheckResult';
import {
    CheckResultFromJSON,
    CheckResultFromJSONTyped,
    CheckResultToJSON,
} from './CheckResult';

/**
 * PermissionCheckResponse is the response message for the Check method in the Permission service.
 * @export
 * @interface PermissionCheckResponse
 */
export interface PermissionCheckResponse {
    /**
     * 
     * @type {CheckResult}
     * @memberof PermissionCheckResponse
     */
    can?: CheckResult;
    /**
     * 
     * @type {PermissionCheckResponseMetadata}
     * @memberof PermissionCheckResponse
     */
    metadata?: PermissionCheckResponseMetadata;
}

/**
 * Check if a given object implements the PermissionCheckResponse interface.
 */
export function instanceOfPermissionCheckResponse(value: object): value is PermissionCheckResponse {
    return true;
}

export function PermissionCheckResponseFromJSON(json: any): PermissionCheckResponse {
    return PermissionCheckResponseFromJSONTyped(json, false);
}

export function PermissionCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'can': json['can'] == null ? undefined : CheckResultFromJSON(json['can']),
        'metadata': json['metadata'] == null ? undefined : PermissionCheckResponseMetadataFromJSON(json['metadata']),
    };
}

export function PermissionCheckResponseToJSON(value?: PermissionCheckResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'can': CheckResultToJSON(value['can']),
        'metadata': PermissionCheckResponseMetadataToJSON(value['metadata']),
    };
}

