/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Expand } from './Expand';
import {
    ExpandFromJSON,
    ExpandFromJSONTyped,
    ExpandToJSON,
} from './Expand';

/**
 * PermissionExpandResponse is the response message for the Expand method in the Permission service.
 * @export
 * @interface PermissionExpandResponse
 */
export interface PermissionExpandResponse {
    /**
     * 
     * @type {Expand}
     * @memberof PermissionExpandResponse
     */
    tree?: Expand;
}

/**
 * Check if a given object implements the PermissionExpandResponse interface.
 */
export function instanceOfPermissionExpandResponse(value: object): value is PermissionExpandResponse {
    return true;
}

export function PermissionExpandResponseFromJSON(json: any): PermissionExpandResponse {
    return PermissionExpandResponseFromJSONTyped(json, false);
}

export function PermissionExpandResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionExpandResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tree': json['tree'] == null ? undefined : ExpandFromJSON(json['tree']),
    };
}

export function PermissionExpandResponseToJSON(value?: PermissionExpandResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tree': ExpandToJSON(value['tree']),
    };
}

