/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PermissionExpandRequestMetadata metadata for the PermissionExpandRequest.
 * @export
 * @interface PermissionExpandRequestMetadata
 */
export interface PermissionExpandRequestMetadata {
    /**
     * Version of the schema.
     * @type {string}
     * @memberof PermissionExpandRequestMetadata
     */
    schemaVersion?: string;
    /**
     * The snap token to avoid stale cache, see more details on [Snap Tokens](../../operations/snap-tokens).
     * @type {string}
     * @memberof PermissionExpandRequestMetadata
     */
    snapToken?: string;
}

/**
 * Check if a given object implements the PermissionExpandRequestMetadata interface.
 */
export function instanceOfPermissionExpandRequestMetadata(value: object): value is PermissionExpandRequestMetadata {
    return true;
}

export function PermissionExpandRequestMetadataFromJSON(json: any): PermissionExpandRequestMetadata {
    return PermissionExpandRequestMetadataFromJSONTyped(json, false);
}

export function PermissionExpandRequestMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionExpandRequestMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'] == null ? undefined : json['schema_version'],
        'snapToken': json['snap_token'] == null ? undefined : json['snap_token'],
    };
}

export function PermissionExpandRequestMetadataToJSON(value?: PermissionExpandRequestMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'schema_version': value['schemaVersion'],
        'snap_token': value['snapToken'],
    };
}

