/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
} from './Context';
import type { Entity } from './Entity';
import {
    EntityFromJSON,
    EntityFromJSONTyped,
    EntityToJSON,
} from './Entity';
import type { PermissionSubjectPermissionRequestMetadata } from './PermissionSubjectPermissionRequestMetadata';
import {
    PermissionSubjectPermissionRequestMetadataFromJSON,
    PermissionSubjectPermissionRequestMetadataFromJSONTyped,
    PermissionSubjectPermissionRequestMetadataToJSON,
} from './PermissionSubjectPermissionRequestMetadata';
import type { Subject } from './Subject';
import {
    SubjectFromJSON,
    SubjectFromJSONTyped,
    SubjectToJSON,
} from './Subject';

/**
 * PermissionSubjectPermissionRequest is the request message for the SubjectPermission method in the Permission service.
 * @export
 * @interface PermissionsSubjectPermissionRequest
 */
export interface PermissionsSubjectPermissionRequest {
    /**
     * 
     * @type {PermissionSubjectPermissionRequestMetadata}
     * @memberof PermissionsSubjectPermissionRequest
     */
    metadata?: PermissionSubjectPermissionRequestMetadata;
    /**
     * 
     * @type {Entity}
     * @memberof PermissionsSubjectPermissionRequest
     */
    entity?: Entity;
    /**
     * 
     * @type {Subject}
     * @memberof PermissionsSubjectPermissionRequest
     */
    subject?: Subject;
    /**
     * 
     * @type {Context}
     * @memberof PermissionsSubjectPermissionRequest
     */
    context?: Context;
}

/**
 * Check if a given object implements the PermissionsSubjectPermissionRequest interface.
 */
export function instanceOfPermissionsSubjectPermissionRequest(value: object): value is PermissionsSubjectPermissionRequest {
    return true;
}

export function PermissionsSubjectPermissionRequestFromJSON(json: any): PermissionsSubjectPermissionRequest {
    return PermissionsSubjectPermissionRequestFromJSONTyped(json, false);
}

export function PermissionsSubjectPermissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionsSubjectPermissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : PermissionSubjectPermissionRequestMetadataFromJSON(json['metadata']),
        'entity': json['entity'] == null ? undefined : EntityFromJSON(json['entity']),
        'subject': json['subject'] == null ? undefined : SubjectFromJSON(json['subject']),
        'context': json['context'] == null ? undefined : ContextFromJSON(json['context']),
    };
}

export function PermissionsSubjectPermissionRequestToJSON(value?: PermissionsSubjectPermissionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metadata': PermissionSubjectPermissionRequestMetadataToJSON(value['metadata']),
        'entity': EntityToJSON(value['entity']),
        'subject': SubjectToJSON(value['subject']),
        'context': ContextToJSON(value['context']),
    };
}

