/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PermissionLookupEntityStreamResponse is the response message for the LookupEntityStream method in the Permission service.
 * @export
 * @interface PermissionLookupEntityStreamResponse
 */
export interface PermissionLookupEntityStreamResponse {
    /**
     * Identifier for an entity that matches the lookup.
     * @type {string}
     * @memberof PermissionLookupEntityStreamResponse
     */
    entityId?: string;
}

/**
 * Check if a given object implements the PermissionLookupEntityStreamResponse interface.
 */
export function instanceOfPermissionLookupEntityStreamResponse(value: object): value is PermissionLookupEntityStreamResponse {
    return true;
}

export function PermissionLookupEntityStreamResponseFromJSON(json: any): PermissionLookupEntityStreamResponse {
    return PermissionLookupEntityStreamResponseFromJSONTyped(json, false);
}

export function PermissionLookupEntityStreamResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionLookupEntityStreamResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entityId': json['entity_id'] == null ? undefined : json['entity_id'],
    };
}

export function PermissionLookupEntityStreamResponseToJSON(value?: PermissionLookupEntityStreamResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'entity_id': value['entityId'],
    };
}

