/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Expand } from './V1Expand';
import {
    V1ExpandFromJSON,
    V1ExpandFromJSONTyped,
    V1ExpandToJSON,
    V1ExpandToJSONTyped,
} from './V1Expand';

/**
 * PermissionExpandResponse is the response message for the Expand method in the Permission service.
 * @export
 * @interface PermissionExpandResponse
 */
export interface PermissionExpandResponse {
    /**
     * 
     * @type {V1Expand}
     * @memberof PermissionExpandResponse
     */
    tree?: V1Expand;
}

/**
 * Check if a given object implements the PermissionExpandResponse interface.
 */
export function instanceOfPermissionExpandResponse(value: object): value is PermissionExpandResponse {
    return true;
}

export function PermissionExpandResponseFromJSON(json: any): PermissionExpandResponse {
    return PermissionExpandResponseFromJSONTyped(json, false);
}

export function PermissionExpandResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionExpandResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tree': json['tree'] == null ? undefined : V1ExpandFromJSON(json['tree']),
    };
}

export function PermissionExpandResponseToJSON(json: any): PermissionExpandResponse {
    return PermissionExpandResponseToJSONTyped(json, false);
}

export function PermissionExpandResponseToJSONTyped(value?: PermissionExpandResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tree': V1ExpandToJSON(value['tree']),
    };
}

