/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PermissionLookupSubjectResponse is the response message for the LookupSubject method in the Permission service.
 * @export
 * @interface PermissionLookupSubjectResponse
 */
export interface PermissionLookupSubjectResponse {
    /**
     * List of identifiers for subjects that match the lookup.
     * @type {Array<string>}
     * @memberof PermissionLookupSubjectResponse
     */
    subjectIds?: Array<string>;
}

/**
 * Check if a given object implements the PermissionLookupSubjectResponse interface.
 */
export function instanceOfPermissionLookupSubjectResponse(value: object): value is PermissionLookupSubjectResponse {
    return true;
}

export function PermissionLookupSubjectResponseFromJSON(json: any): PermissionLookupSubjectResponse {
    return PermissionLookupSubjectResponseFromJSONTyped(json, false);
}

export function PermissionLookupSubjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionLookupSubjectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'subjectIds': json['subject_ids'] == null ? undefined : json['subject_ids'],
    };
}

export function PermissionLookupSubjectResponseToJSON(value?: PermissionLookupSubjectResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'subject_ids': value['subjectIds'],
    };
}

