/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Child } from './Child';
import {
    ChildFromJSON,
    ChildFromJSONTyped,
    ChildToJSON,
} from './Child';

/**
 * The PermissionDefinition message provides detailed information about a specific permission.
 * @export
 * @interface PermissionDefinition
 */
export interface PermissionDefinition {
    /**
     * The name of the permission, which follows a specific string pattern and has a maximum byte size.
     * @type {string}
     * @memberof PermissionDefinition
     */
    name?: string;
    /**
     * 
     * @type {Child}
     * @memberof PermissionDefinition
     */
    child?: Child;
}

/**
 * Check if a given object implements the PermissionDefinition interface.
 */
export function instanceOfPermissionDefinition(value: object): value is PermissionDefinition {
    return true;
}

export function PermissionDefinitionFromJSON(json: any): PermissionDefinition {
    return PermissionDefinitionFromJSONTyped(json, false);
}

export function PermissionDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'child': json['child'] == null ? undefined : ChildFromJSON(json['child']),
    };
}

export function PermissionDefinitionToJSON(value?: PermissionDefinition | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'child': ChildToJSON(value['child']),
    };
}

