/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PermissionLookupEntityResponse is the response message for the LookupEntity method in the Permission service.
 * @export
 * @interface PermissionLookupEntityResponse
 */
export interface PermissionLookupEntityResponse {
    /**
     * List of identifiers for entities that match the lookup.
     * @type {Array<string>}
     * @memberof PermissionLookupEntityResponse
     */
    entityIds?: Array<string>;
}

/**
 * Check if a given object implements the PermissionLookupEntityResponse interface.
 */
export function instanceOfPermissionLookupEntityResponse(value: object): value is PermissionLookupEntityResponse {
    return true;
}

export function PermissionLookupEntityResponseFromJSON(json: any): PermissionLookupEntityResponse {
    return PermissionLookupEntityResponseFromJSONTyped(json, false);
}

export function PermissionLookupEntityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionLookupEntityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entityIds': json['entity_ids'] == null ? undefined : json['entity_ids'],
    };
}

export function PermissionLookupEntityResponseToJSON(value?: PermissionLookupEntityResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'entity_ids': value['entityIds'],
    };
}

