/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PermissionCheckResponseMetadata metadata for the PermissionCheckResponse.
 * @export
 * @interface PermissionCheckResponseMetadata
 */
export interface PermissionCheckResponseMetadata {
    /**
     * The count of the checks performed.
     * @type {number}
     * @memberof PermissionCheckResponseMetadata
     */
    checkCount?: number;
}

/**
 * Check if a given object implements the PermissionCheckResponseMetadata interface.
 */
export function instanceOfPermissionCheckResponseMetadata(value: object): value is PermissionCheckResponseMetadata {
    return true;
}

export function PermissionCheckResponseMetadataFromJSON(json: any): PermissionCheckResponseMetadata {
    return PermissionCheckResponseMetadataFromJSONTyped(json, false);
}

export function PermissionCheckResponseMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionCheckResponseMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'checkCount': json['check_count'] == null ? undefined : json['check_count'],
    };
}

export function PermissionCheckResponseMetadataToJSON(value?: PermissionCheckResponseMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'check_count': value['checkCount'],
    };
}

