/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * RelationshipReadRequestMetadata defines the structure of the metadata for a read request focused on relationships.
 * It includes the snap_token associated with a particular state of the database.
 * @export
 * @interface RelationshipReadRequestMetadata
 */
export interface RelationshipReadRequestMetadata {
    /**
     * The snap token to avoid stale cache, see more details on [Snap Tokens](../../operations/snap-tokens)
     * @type {string}
     * @memberof RelationshipReadRequestMetadata
     */
    snapToken?: string;
}

/**
 * Check if a given object implements the RelationshipReadRequestMetadata interface.
 */
export function instanceOfRelationshipReadRequestMetadata(value: object): value is RelationshipReadRequestMetadata {
    return true;
}

export function RelationshipReadRequestMetadataFromJSON(json: any): RelationshipReadRequestMetadata {
    return RelationshipReadRequestMetadataFromJSONTyped(json, false);
}

export function RelationshipReadRequestMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationshipReadRequestMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'snapToken': json['snap_token'] == null ? undefined : json['snap_token'],
    };
}

export function RelationshipReadRequestMetadataToJSON(value?: RelationshipReadRequestMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'snap_token': value['snapToken'],
    };
}

