/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RelationshipWriteRequestMetadata
 */
export interface RelationshipWriteRequestMetadata {
    /**
     * 
     * @type {string}
     * @memberof RelationshipWriteRequestMetadata
     */
    schemaVersion?: string;
}

/**
 * Check if a given object implements the RelationshipWriteRequestMetadata interface.
 */
export function instanceOfRelationshipWriteRequestMetadata(value: object): value is RelationshipWriteRequestMetadata {
    return true;
}

export function RelationshipWriteRequestMetadataFromJSON(json: any): RelationshipWriteRequestMetadata {
    return RelationshipWriteRequestMetadataFromJSONTyped(json, false);
}

export function RelationshipWriteRequestMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationshipWriteRequestMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'] == null ? undefined : json['schema_version'],
    };
}

export function RelationshipWriteRequestMetadataToJSON(value?: RelationshipWriteRequestMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'schema_version': value['schemaVersion'],
    };
}

