/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The RelationReference message provides a reference to a specific relation.
 * @export
 * @interface RelationReference
 */
export interface RelationReference {
    /**
     * The type of the referenced entity, which follows a specific string pattern and has a maximum byte size.
     * @type {string}
     * @memberof RelationReference
     */
    type?: string;
    /**
     * The name of the referenced relation, which follows a specific string pattern and has a maximum byte size.
     * @type {string}
     * @memberof RelationReference
     */
    relation?: string;
}

/**
 * Check if a given object implements the RelationReference interface.
 */
export function instanceOfRelationReference(value: object): value is RelationReference {
    return true;
}

export function RelationReferenceFromJSON(json: any): RelationReference {
    return RelationReferenceFromJSONTyped(json, false);
}

export function RelationReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationReference {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'relation': json['relation'] == null ? undefined : json['relation'],
    };
}

export function RelationReferenceToJSON(value?: RelationReference | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'relation': value['relation'],
    };
}

