/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * BundleRunRequest is used to request the execution of a bundle.
 * It includes tenant_id, the name of the bundle, and additional arguments for execution.
 * @export
 * @interface RunBundleBody
 */
export interface RunBundleBody {
    /**
     * Name of the bundle to be executed.
     * @type {string}
     * @memberof RunBundleBody
     */
    name?: string;
    /**
     * Additional key-value pairs for execution arguments.
     * @type {{ [key: string]: string; }}
     * @memberof RunBundleBody
     */
    arguments?: { [key: string]: string; };
}

/**
 * Check if a given object implements the RunBundleBody interface.
 */
export function instanceOfRunBundleBody(value: object): value is RunBundleBody {
    return true;
}

export function RunBundleBodyFromJSON(json: any): RunBundleBody {
    return RunBundleBodyFromJSONTyped(json, false);
}

export function RunBundleBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunBundleBody {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'arguments': json['arguments'] == null ? undefined : json['arguments'],
    };
}

export function RunBundleBodyToJSON(json: any): RunBundleBody {
    return RunBundleBodyToJSONTyped(json, false);
}

export function RunBundleBodyToJSONTyped(value?: RunBundleBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'arguments': value['arguments'],
    };
}

