/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * SchemaListRequest is the request message for the List method in the Schema service.
 * It contains tenant_id for which the schemas are to be listed.
 * @export
 * @interface SchemasListRequest
 */
export interface SchemasListRequest {
    /**
     * page_size is the number of tenants to be returned in the response.
     * The value should be between 1 and 100.
     * @type {number}
     * @memberof SchemasListRequest
     */
    pageSize?: number;
    /**
     * continuous_token is an optional parameter used for pagination.
     * It should be the value received in the previous response.
     * @type {string}
     * @memberof SchemasListRequest
     */
    continuousToken?: string;
}

/**
 * Check if a given object implements the SchemasListRequest interface.
 */
export function instanceOfSchemasListRequest(value: object): value is SchemasListRequest {
    return true;
}

export function SchemasListRequestFromJSON(json: any): SchemasListRequest {
    return SchemasListRequestFromJSONTyped(json, false);
}

export function SchemasListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemasListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'continuousToken': json['continuous_token'] == null ? undefined : json['continuous_token'],
    };
}

export function SchemasListRequestToJSON(value?: SchemasListRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page_size': value['pageSize'],
        'continuous_token': value['continuousToken'],
    };
}

