/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The Reference enum helps distinguish whether a name corresponds to an entity or a rule.
 * 
 *  - REFERENCE_UNSPECIFIED: Default, unspecified reference.
 *  - REFERENCE_ENTITY: Indicates that the name refers to an entity.
 *  - REFERENCE_RULE: Indicates that the name refers to a rule.
 * @export
 */
export const SchemaDefinitionReference = {
    Unspecified: 'REFERENCE_UNSPECIFIED',
    Entity: 'REFERENCE_ENTITY',
    Rule: 'REFERENCE_RULE'
} as const;
export type SchemaDefinitionReference = typeof SchemaDefinitionReference[keyof typeof SchemaDefinitionReference];


export function instanceOfSchemaDefinitionReference(value: any): boolean {
    for (const key in SchemaDefinitionReference) {
        if (Object.prototype.hasOwnProperty.call(SchemaDefinitionReference, key)) {
            if ((SchemaDefinitionReference as Record<string, SchemaDefinitionReference>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SchemaDefinitionReferenceFromJSON(json: any): SchemaDefinitionReference {
    return SchemaDefinitionReferenceFromJSONTyped(json, false);
}

export function SchemaDefinitionReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaDefinitionReference {
    return json as SchemaDefinitionReference;
}

export function SchemaDefinitionReferenceToJSON(value?: SchemaDefinitionReference | null): any {
    return value as any;
}

