/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SchemaReadRequestMetadata } from './SchemaReadRequestMetadata';
import {
    SchemaReadRequestMetadataFromJSON,
    SchemaReadRequestMetadataFromJSONTyped,
    SchemaReadRequestMetadataToJSON,
    SchemaReadRequestMetadataToJSONTyped,
} from './SchemaReadRequestMetadata';

/**
 * SchemaReadRequest is the request message for the Read method in the Schema service.
 * It contains tenant_id and metadata about the schema to be read.
 * @export
 * @interface SchemaReadBody
 */
export interface SchemaReadBody {
    /**
     * 
     * @type {SchemaReadRequestMetadata}
     * @memberof SchemaReadBody
     */
    metadata?: SchemaReadRequestMetadata;
}

/**
 * Check if a given object implements the SchemaReadBody interface.
 */
export function instanceOfSchemaReadBody(value: object): value is SchemaReadBody {
    return true;
}

export function SchemaReadBodyFromJSON(json: any): SchemaReadBody {
    return SchemaReadBodyFromJSONTyped(json, false);
}

export function SchemaReadBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaReadBody {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : SchemaReadRequestMetadataFromJSON(json['metadata']),
    };
}

export function SchemaReadBodyToJSON(json: any): SchemaReadBody {
    return SchemaReadBodyToJSONTyped(json, false);
}

export function SchemaReadBodyToJSONTyped(value?: SchemaReadBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': SchemaReadRequestMetadataToJSON(value['metadata']),
    };
}

