/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * SchemaListRequest is the request message for the List method in the Schema service.
 * It contains tenant_id for which the schemas are to be listed.
 * @export
 * @interface SchemaListBody
 */
export interface SchemaListBody {
    /**
     * page_size is the number of schemas to be returned in the response.
     * The value should be between 1 and 100.
     * @type {number}
     * @memberof SchemaListBody
     */
    pageSize?: number;
    /**
     * continuous_token is an optional parameter used for pagination.
     * It should be the value received in the previous response.
     * @type {string}
     * @memberof SchemaListBody
     */
    continuousToken?: string;
}

/**
 * Check if a given object implements the SchemaListBody interface.
 */
export function instanceOfSchemaListBody(value: object): value is SchemaListBody {
    return true;
}

export function SchemaListBodyFromJSON(json: any): SchemaListBody {
    return SchemaListBodyFromJSONTyped(json, false);
}

export function SchemaListBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaListBody {
    if (json == null) {
        return json;
    }
    return {
        
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'continuousToken': json['continuous_token'] == null ? undefined : json['continuous_token'],
    };
}

export function SchemaListBodyToJSON(json: any): SchemaListBody {
    return SchemaListBodyToJSONTyped(json, false);
}

export function SchemaListBodyToJSONTyped(value?: SchemaListBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page_size': value['pageSize'],
        'continuous_token': value['continuousToken'],
    };
}

