/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemaList
 */
export interface SchemaList {
    /**
     * 
     * @type {string}
     * @memberof SchemaList
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaList
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the SchemaList interface.
 */
export function instanceOfSchemaList(value: object): value is SchemaList {
    return true;
}

export function SchemaListFromJSON(json: any): SchemaList {
    return SchemaListFromJSONTyped(json, false);
}

export function SchemaListFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaList {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
    };
}

export function SchemaListToJSON(value?: SchemaList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'version': value['version'],
        'created_at': value['createdAt'],
    };
}

