/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * SchemaWriteRequest is the request message for the Write method in the Schema service.
 * It contains tenant_id and the schema to be written.
 * @export
 * @interface SchemaWriteBody
 */
export interface SchemaWriteBody {
    /**
     * schema is the string representation of the schema to be written.
     * @type {string}
     * @memberof SchemaWriteBody
     */
    schema?: string;
}

/**
 * Check if a given object implements the SchemaWriteBody interface.
 */
export function instanceOfSchemaWriteBody(value: object): value is SchemaWriteBody {
    return true;
}

export function SchemaWriteBodyFromJSON(json: any): SchemaWriteBody {
    return SchemaWriteBodyFromJSONTyped(json, false);
}

export function SchemaWriteBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaWriteBody {
    if (json == null) {
        return json;
    }
    return {
        
        'schema': json['schema'] == null ? undefined : json['schema'],
    };
}

export function SchemaWriteBodyToJSON(json: any): SchemaWriteBody {
    return SchemaWriteBodyToJSONTyped(json, false);
}

export function SchemaWriteBodyToJSONTyped(value?: SchemaWriteBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema': value['schema'],
    };
}

