/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Wrapper for an array of strings.
 * @export
 * @interface StringArrayValue
 */
export interface StringArrayValue {
    /**
     * The array of strings.
     * @type {Array<string>}
     * @memberof StringArrayValue
     */
    data?: Array<string>;
}

/**
 * Check if a given object implements the StringArrayValue interface.
 */
export function instanceOfStringArrayValue(value: object): value is StringArrayValue {
    return true;
}

export function StringArrayValueFromJSON(json: any): StringArrayValue {
    return StringArrayValueFromJSONTyped(json, false);
}

export function StringArrayValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): StringArrayValue {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function StringArrayValueToJSON(json: any): StringArrayValue {
    return StringArrayValueToJSONTyped(json, false);
}

export function StringArrayValueToJSONTyped(value?: StringArrayValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

