/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { Entity } from './Entity';
import {
    EntityFromJSON,
    EntityFromJSONTyped,
    EntityToJSON,
    EntityToJSONTyped,
} from './Entity';
import type { PermissionSubjectPermissionRequestMetadata } from './PermissionSubjectPermissionRequestMetadata';
import {
    PermissionSubjectPermissionRequestMetadataFromJSON,
    PermissionSubjectPermissionRequestMetadataFromJSONTyped,
    PermissionSubjectPermissionRequestMetadataToJSON,
    PermissionSubjectPermissionRequestMetadataToJSONTyped,
} from './PermissionSubjectPermissionRequestMetadata';
import type { Subject } from './Subject';
import {
    SubjectFromJSON,
    SubjectFromJSONTyped,
    SubjectToJSON,
    SubjectToJSONTyped,
} from './Subject';

/**
 * PermissionSubjectPermissionRequest is the request message for the SubjectPermission method in the Permission service.
 * @export
 * @interface SubjectPermissionBody
 */
export interface SubjectPermissionBody {
    /**
     * 
     * @type {PermissionSubjectPermissionRequestMetadata}
     * @memberof SubjectPermissionBody
     */
    metadata?: PermissionSubjectPermissionRequestMetadata;
    /**
     * 
     * @type {Entity}
     * @memberof SubjectPermissionBody
     */
    entity?: Entity;
    /**
     * 
     * @type {Subject}
     * @memberof SubjectPermissionBody
     */
    subject?: Subject;
    /**
     * 
     * @type {Context}
     * @memberof SubjectPermissionBody
     */
    context?: Context;
}

/**
 * Check if a given object implements the SubjectPermissionBody interface.
 */
export function instanceOfSubjectPermissionBody(value: object): value is SubjectPermissionBody {
    return true;
}

export function SubjectPermissionBodyFromJSON(json: any): SubjectPermissionBody {
    return SubjectPermissionBodyFromJSONTyped(json, false);
}

export function SubjectPermissionBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectPermissionBody {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : PermissionSubjectPermissionRequestMetadataFromJSON(json['metadata']),
        'entity': json['entity'] == null ? undefined : EntityFromJSON(json['entity']),
        'subject': json['subject'] == null ? undefined : SubjectFromJSON(json['subject']),
        'context': json['context'] == null ? undefined : ContextFromJSON(json['context']),
    };
}

export function SubjectPermissionBodyToJSON(json: any): SubjectPermissionBody {
    return SubjectPermissionBodyToJSONTyped(json, false);
}

export function SubjectPermissionBodyToJSONTyped(value?: SubjectPermissionBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': PermissionSubjectPermissionRequestMetadataToJSON(value['metadata']),
        'entity': EntityToJSON(value['entity']),
        'subject': SubjectToJSON(value['subject']),
        'context': ContextToJSON(value['context']),
    };
}

