/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * SubjectFilter is used to filter subjects based on the type, ids and relation.
 * @export
 * @interface SubjectFilter
 */
export interface SubjectFilter {
    /**
     * 
     * @type {string}
     * @memberof SubjectFilter
     */
    type?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SubjectFilter
     */
    ids?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SubjectFilter
     */
    relation?: string;
}

/**
 * Check if a given object implements the SubjectFilter interface.
 */
export function instanceOfSubjectFilter(value: object): value is SubjectFilter {
    return true;
}

export function SubjectFilterFromJSON(json: any): SubjectFilter {
    return SubjectFilterFromJSONTyped(json, false);
}

export function SubjectFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'ids': json['ids'] == null ? undefined : json['ids'],
        'relation': json['relation'] == null ? undefined : json['relation'],
    };
}

export function SubjectFilterToJSON(value?: SubjectFilter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'ids': value['ids'],
        'relation': value['relation'],
    };
}

