/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * TenantCreateRequest is the message used for the request to create a tenant.
 * @export
 * @interface TenantCreateRequest
 */
export interface TenantCreateRequest {
    /**
     * id is a unique identifier for the tenant.
     * @type {string}
     * @memberof TenantCreateRequest
     */
    id?: string;
    /**
     * name is the name of the tenant.
     * @type {string}
     * @memberof TenantCreateRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the TenantCreateRequest interface.
 */
export function instanceOfTenantCreateRequest(value: object): value is TenantCreateRequest {
    return true;
}

export function TenantCreateRequestFromJSON(json: any): TenantCreateRequest {
    return TenantCreateRequestFromJSONTyped(json, false);
}

export function TenantCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function TenantCreateRequestToJSON(value?: TenantCreateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

