/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tenant } from './Tenant';
import {
    TenantFromJSON,
    TenantFromJSONTyped,
    TenantToJSON,
} from './Tenant';

/**
 * TenantCreateResponse is the message returned from the request to create a tenant.
 * @export
 * @interface TenantCreateResponse
 */
export interface TenantCreateResponse {
    /**
     * 
     * @type {Tenant}
     * @memberof TenantCreateResponse
     */
    tenant?: Tenant;
}

/**
 * Check if a given object implements the TenantCreateResponse interface.
 */
export function instanceOfTenantCreateResponse(value: object): value is TenantCreateResponse {
    return true;
}

export function TenantCreateResponseFromJSON(json: any): TenantCreateResponse {
    return TenantCreateResponseFromJSONTyped(json, false);
}

export function TenantCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tenant': json['tenant'] == null ? undefined : TenantFromJSON(json['tenant']),
    };
}

export function TenantCreateResponseToJSON(value?: TenantCreateResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tenant': TenantToJSON(value['tenant']),
    };
}

