/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tenant } from './Tenant';
import {
    TenantFromJSON,
    TenantFromJSONTyped,
    TenantToJSON,
} from './Tenant';

/**
 * TenantDeleteResponse is the message returned from the request to delete a tenant.
 * @export
 * @interface TenantDeleteResponse
 */
export interface TenantDeleteResponse {
    /**
     * 
     * @type {Tenant}
     * @memberof TenantDeleteResponse
     */
    tenant?: Tenant;
}

/**
 * Check if a given object implements the TenantDeleteResponse interface.
 */
export function instanceOfTenantDeleteResponse(value: object): value is TenantDeleteResponse {
    return true;
}

export function TenantDeleteResponseFromJSON(json: any): TenantDeleteResponse {
    return TenantDeleteResponseFromJSONTyped(json, false);
}

export function TenantDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tenant': json['tenant'] == null ? undefined : TenantFromJSON(json['tenant']),
    };
}

export function TenantDeleteResponseToJSON(value?: TenantDeleteResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tenant': TenantToJSON(value['tenant']),
    };
}

