/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * TenantDeleteResponse is the message returned from the request to delete a tenant.
 * @export
 * @interface TenantDeleteResponse
 */
export interface TenantDeleteResponse {
    /**
     * tenant_id is the tenant id that was deleted.
     * @type {string}
     * @memberof TenantDeleteResponse
     */
    tenantId?: string;
}

/**
 * Check if a given object implements the TenantDeleteResponse interface.
 */
export function instanceOfTenantDeleteResponse(value: object): value is TenantDeleteResponse {
    return true;
}

export function TenantDeleteResponseFromJSON(json: any): TenantDeleteResponse {
    return TenantDeleteResponseFromJSONTyped(json, false);
}

export function TenantDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tenantId': json['tenant_id'] == null ? undefined : json['tenant_id'],
    };
}

export function TenantDeleteResponseToJSON(json: any): TenantDeleteResponse {
    return TenantDeleteResponseToJSONTyped(json, false);
}

export function TenantDeleteResponseToJSONTyped(value?: TenantDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenant_id': value['tenantId'],
    };
}

