/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * TupleSet represents a set of tuples associated with a specific relation.
 * @export
 * @interface TupleSet
 */
export interface TupleSet {
    /**
     * 
     * @type {string}
     * @memberof TupleSet
     */
    relation?: string;
}

/**
 * Check if a given object implements the TupleSet interface.
 */
export function instanceOfTupleSet(value: object): value is TupleSet {
    return true;
}

export function TupleSetFromJSON(json: any): TupleSet {
    return TupleSetFromJSONTyped(json, false);
}

export function TupleSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): TupleSet {
    if (json == null) {
        return json;
    }
    return {
        
        'relation': json['relation'] == null ? undefined : json['relation'],
    };
}

export function TupleSetToJSON(value?: TupleSet | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'relation': value['relation'],
    };
}

