/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Any } from './Any';
import {
    AnyFromJSON,
    AnyFromJSONTyped,
    AnyToJSON,
    AnyToJSONTyped,
} from './Any';

/**
 * 
 * @export
 * @interface Values
 */
export interface Values {
    /**
     * 
     * @type {{ [key: string]: Any; }}
     * @memberof Values
     */
    values?: { [key: string]: Any; };
}

/**
 * Check if a given object implements the Values interface.
 */
export function instanceOfValues(value: object): value is Values {
    return true;
}

export function ValuesFromJSON(json: any): Values {
    return ValuesFromJSONTyped(json, false);
}

export function ValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Values {
    if (json == null) {
        return json;
    }
    return {
        
        'values': json['values'] == null ? undefined : (mapValues(json['values'], AnyFromJSON)),
    };
}

export function ValuesToJSON(json: any): Values {
    return ValuesToJSONTyped(json, false);
}

export function ValuesToJSONTyped(value?: Values | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'values': value['values'] == null ? undefined : (mapValues(value['values'], AnyToJSON)),
    };
}

