/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * WatchRequest is the request message for the Watch RPC. It contains the
 * details needed to establish a watch stream.
 * @export
 * @interface WatchWatchRequest
 */
export interface WatchWatchRequest {
    /**
     * The snap token to avoid stale cache, see more details on [Snap Tokens](../../operations/snap-tokens).
     * @type {string}
     * @memberof WatchWatchRequest
     */
    snapToken?: string;
}

/**
 * Check if a given object implements the WatchWatchRequest interface.
 */
export function instanceOfWatchWatchRequest(value: object): value is WatchWatchRequest {
    return true;
}

export function WatchWatchRequestFromJSON(json: any): WatchWatchRequest {
    return WatchWatchRequestFromJSONTyped(json, false);
}

export function WatchWatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchWatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'snapToken': json['snap_token'] == null ? undefined : json['snap_token'],
    };
}

export function WatchWatchRequestToJSON(value?: WatchWatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'snap_token': value['snapToken'],
    };
}

