/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * WatchRequest is the request message for the Watch RPC. It contains the
 * details needed to establish a watch stream.
 * @export
 * @interface WatchBody
 */
export interface WatchBody {
    /**
     * The snap token to avoid stale cache, see more details on [Snap Tokens](../../operations/snap-tokens).
     * @type {string}
     * @memberof WatchBody
     */
    snapToken?: string;
}

/**
 * Check if a given object implements the WatchBody interface.
 */
export function instanceOfWatchBody(value: object): value is WatchBody {
    return true;
}

export function WatchBodyFromJSON(json: any): WatchBody {
    return WatchBodyFromJSONTyped(json, false);
}

export function WatchBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatchBody {
    if (json == null) {
        return json;
    }
    return {
        
        'snapToken': json['snap_token'] == null ? undefined : json['snap_token'],
    };
}

export function WatchBodyToJSON(json: any): WatchBody {
    return WatchBodyToJSONTyped(json, false);
}

export function WatchBodyToJSONTyped(value?: WatchBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'snap_token': value['snapToken'],
    };
}

