/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Well-known protobuf types treated with first-class support in CEL.
 * 
 *  - WELL_KNOWN_TYPE_UNSPECIFIED: Unspecified type.
 *  - ANY: Well-known protobuf.Any type.
 * 
 * Any types are a polymorphic message type. During type-checking they are
 * treated like `DYN` types, but at runtime they are resolved to a specific
 * message type specified at evaluation time.
 *  - TIMESTAMP: Well-known protobuf.Timestamp type, internally referenced as `timestamp`.
 *  - DURATION: Well-known protobuf.Duration type, internally referenced as `duration`.
 * @export
 */
export const WellKnownType = {
    WellKnownTypeUnspecified: 'WELL_KNOWN_TYPE_UNSPECIFIED',
    Any: 'ANY',
    Timestamp: 'TIMESTAMP',
    Duration: 'DURATION'
} as const;
export type WellKnownType = typeof WellKnownType[keyof typeof WellKnownType];


export function instanceOfWellKnownType(value: any): boolean {
    for (const key in WellKnownType) {
        if (Object.prototype.hasOwnProperty.call(WellKnownType, key)) {
            if ((WellKnownType as Record<string, WellKnownType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WellKnownTypeFromJSON(json: any): WellKnownType {
    return WellKnownTypeFromJSONTyped(json, false);
}

export function WellKnownTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WellKnownType {
    return json as WellKnownType;
}

export function WellKnownTypeToJSON(value?: WellKnownType | null): any {
    return value as any;
}

