/* tslint:disable */
/* eslint-disable */
/**
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.6.8
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelationshipWriteRequestMetadata } from './RelationshipWriteRequestMetadata';
import {
    RelationshipWriteRequestMetadataFromJSON,
    RelationshipWriteRequestMetadataFromJSONTyped,
    RelationshipWriteRequestMetadataToJSON,
    RelationshipWriteRequestMetadataToJSONTyped,
} from './RelationshipWriteRequestMetadata';
import type { Tuple } from './Tuple';
import {
    TupleFromJSON,
    TupleFromJSONTyped,
    TupleToJSON,
    TupleToJSONTyped,
} from './Tuple';

/**
 * Represents a request to write relationship data.
 * @export
 * @interface WriteRelationshipsBody
 */
export interface WriteRelationshipsBody {
    /**
     * 
     * @type {RelationshipWriteRequestMetadata}
     * @memberof WriteRelationshipsBody
     */
    metadata?: RelationshipWriteRequestMetadata;
    /**
     * List of tuples for the request. Must have between 1 and 100 items.
     * @type {Array<Tuple>}
     * @memberof WriteRelationshipsBody
     */
    tuples?: Array<Tuple>;
}

/**
 * Check if a given object implements the WriteRelationshipsBody interface.
 */
export function instanceOfWriteRelationshipsBody(value: object): value is WriteRelationshipsBody {
    return true;
}

export function WriteRelationshipsBodyFromJSON(json: any): WriteRelationshipsBody {
    return WriteRelationshipsBodyFromJSONTyped(json, false);
}

export function WriteRelationshipsBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteRelationshipsBody {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : RelationshipWriteRequestMetadataFromJSON(json['metadata']),
        'tuples': json['tuples'] == null ? undefined : ((json['tuples'] as Array<any>).map(TupleFromJSON)),
    };
}

export function WriteRelationshipsBodyToJSON(json: any): WriteRelationshipsBody {
    return WriteRelationshipsBodyToJSONTyped(json, false);
}

export function WriteRelationshipsBodyToJSONTyped(value?: WriteRelationshipsBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': RelationshipWriteRequestMetadataToJSON(value['metadata']),
        'tuples': value['tuples'] == null ? undefined : ((value['tuples'] as Array<any>).map(TupleToJSON)),
    };
}

